- name: create vogon user
  user:
    name: vogon-web
    groups: webapps
    state: present
  become: yes
- name: create project directory
  file:
    path: /var/opt/wsgi/vogon-web
    state: directory
    owner: vogon-web
    group: webapps
  become: yes
- name: create app subdirectories
  file:
    path: /var/opt/wsgi/vogon-web/{{ item }}
    state: directory
    mode: "u=rwx,g=rwx,o="
    owner: vogon-web
    group: webapps
  become: yes
  with_items:
    - run
    - bin
    - logs
    - static
    - media
- name: create media directory
  file:
    path: "{{ vogon-web_media_root }}"
    state: directory
    mode: "u=rwx,g=rwx,o="
    owner: vogon-web
    group: webapps
  become: yes
- name: allow nginx to read/write
  command: chcon -Rt httpd_sys_content_t /var/opt/wsgi/vogon-web
  become: yes
- name: write secret environment variables
  template:
    src: env_secrets.j2
    dest: /var/opt/wsgi/vogon-web/env_secrets
    owner: vogon-web
    group: webapps
    mode: "u=rwx,g=,o="
  become: yes
- name: create celery worker log file
  file:
    path: /var/opt/wsgi/vogon-web/logs/celery-worker.log
    state: touch
    owner: vogon-web
    group: webapps
    mode: "u=rw,g=rw,o=r"
  become: yes
