- name: make sure git is installed
  yum:
    name: git
    state: present
  become: yes
- name: make sure virtualenv is installed
  pip:
    name: virtualenv
    state: present
  become: yes
- name: create git repo target
  file:
    path: /var/opt/wsgi/vogon-web/vogon-web
    state: directory
    owner: vogon-web
    mode: "u=rwx,g=r,o=r"
    group: webapps
  become: yes
- name: get code from github
  git:
    repo: git://github.com/diging/vogon-web.git
    dest: /var/opt/wsgi/vogon-web/vogon-web
    force: yes
    version: story/VGNWB-195
  become: yes
  become_user: vogon-web
