#!/bin/bash

NAME="vogon-web"                                  # Name of the application
DJANGODIR=/var/opt/wsgi/vogon-web/vogon-web             # Django project directory
SOCKFILE=/var/opt/wsgi/vogon-web/run/vogon.sock  # we will communicte using this unix socket
USER=vogon                                        # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=vogon.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=vogon.wsgi                     # WSGI module name
DJANGO_CELERY_MODULE=vogon.celery                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../env/bin/activate
source ../env_secrets
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH


exec ../env/bin/celery --app=${DJANGO_CELERY_MODULE}:app worker --loglevel=INFO
